### ISSUE TITLE
IP salvati in consents

### ISSUE THREAD

**Issue by mariobarretta** [diegolamonica/EUCookieLaw3-wp#5]
Dopo varie peripezie sono riuscito a far apparire la sezione consents nella dashboard di WP ma ho ritrovato, al suo interno, svariati ip salvati.
Ciò non può essere un problema proprio per il GDPR per il quale, paradossalmente, si sta cercando di rispettare grazie a questo bel plug in ?

**Comment by diegolamonica** [comment]
L'indirizzo IP è associabile ad un'utenza solo ed esclusivamente dall'internet provider, di conseguenza, inoltre EUCookieLaw lo utilizza non per aggregare informazioni statistiche ma per garantire la validità del consenso fornito dall'utente. 

[In questo articolo](https://diegolamonica.info/eucookielaw-3-0-registrare-il-consenso-dellutente/) ho descritto in dettaglio le motivazioni di questa scelta:

**Comment by mariobarretta** [comment]
Avevo letto il tuo articolo e "compreso" le motivazioni però il dubbio legato al fatto che si salvino degli indirizzi IP mi rimane e discutendo con dei dev mi è stato perentoriamente indicato come una infrazione del GDPR.
Convengo con le tue osservazioni e sulle motivazioni ma, a tuo avviso, il rischio di un'affermazione come quella rivoltami è fondato o lo posso non prendere in considerazione in virtù del fatto che hai salvato queste informazioni non associate ai cookie ma in "local storage" ? 
pongo questa domanda per acquisire know how da replicare a coloro che mi potranno porre la medesima affermazione senza fornire loro "solo" il link al tuo esaustivo articolo

**Comment by diegolamonica** [comment]
Considerando che anche io sono un tecnico e non un avvocato, il mio è un parere potenzialmente contrastante.

Penso che una certezza a riguardo più concreta non possa fornirtela un tecnico (tanto meno io) ma forse un avvocato con competenze sia in materia di GDPR che Web.

**Comment by mariobarretta** [comment]
Capisco perfettamente, per questi sottoporrò il tuo articolo a dei legali e vediamo che cosa mi rispondono a tal riguardo.
Grazie

**Comment by diegolamonica** [comment]
Se ti è possibile, una volta acquisito il parere legale se lo condividessi sarebbe di grande utilità per tutti

**Comment by mariobarretta** [comment]
certamente

**Comment by mariobarretta** [comment]
Le prime osservazioni(interpretazioni "legalesi" parrebbero propendere per la non liceità del salvataggio ip considerando essi come un identificativo personale dell'utente.
Vero è che , per questioni tecniche quello specifico ip può essere utilizzato anche da altri soggetti ma proprio l'accoppiamento con altri parametri fa si che si tratti di un'informazione univoca e quindi legata alla privacy dello specifico utente.
La legge è comunque, purtroppo o per fortuna, ancora troppo nuova e soggetta all'interpretazione del lettore e questo è un grave problema per il quale, di prassi, l'atteggiamento  "consigliato" è quello di propendere per un'azione preventiva che è poi quella di considerare non lecito il salvataggio, in quella forma, di quegli indirizzi IP.

**Comment by diegolamonica** [comment]
Vista la tua considerazione che ritengo legittima valida, nella nuova release di EUCookieLaw3 (v 20180614) ho provveduto ad anonimizzare in fase di Visualizzazione l'IP.

Grazie del contributo.

**Comment by mariobarretta** [comment]
Grazie mille.
Attendo con curiosità la nuova versione.
**P.s.** mi potresti dare [un riscontro](https://github.com/diegolamonica/EUCookieLaw3/issues/8) ?
