### ISSUE TITLE
Cookies are not deleted when consent is initially granted and then revoked

### ISSUE THREAD

**Issue by illtellyoulater** [diegolamonica/EUCookieLaw3-wp#8]
Hi Diego,

**I've observed that if I give consent to cookies, and then I revoke the consent, the cookies will not be deleted.** 

_I previously opened this issue at standalone EUCookieLaw3 repository, but then I started using the plugin from this repo in a wordpress website and I noticed the same problem, so I am also leaving this note here. Hope it helps._

**Comment by diegolamonica** [comment]
Hi @jjgh this is not related to WordPress plugin or standalone library (as mentioned in [library project issue #11](https://github.com/diegolamonica/EUCookieLaw3/issues/11))  but is due to how the browser works.
I will close this issue and will continue conversation on the other (project) repo.
